const { Track } = require("../models");

const trackData = [
  {
    available_picks: [
      "49ers",
      "Bears",
      "Bengals",
      "Bills",
      "Broncos",
      "Browns",
      "Cardinals",
      "Chiefs",
      "Colts",
      "Cowboys",
      "Dolphins",
      "Eagles",
      "Falcons",
      "Giants",
      "Jaguars",
      "Lions",
      "Packers",
      "Panthers",
      "Raiders",
      "Rams",
      "Ravens",
      "Commanders",
      "Saints",
      "Seahawks",
      "Steelers",
      "Buccaneers",
      "Texans",
      "Titans",
      "Vikings",
    ],
    used_picks: ["Jets"],
    current_pick: "Steelers",
    user_id: 1,
  },
  {
    available_picks: [
      "49ers",
      "Bears",
      "Bengals",
      "Bills",
      "Broncos",
      "Browns",
      "Cardinals",
      "Chiefs",
      "Colts",
      "Cowboys",
      "Dolphins",
      "Eagles",
      "Falcons",
      "Giants",
      "Jaguars",
      "Jets",
      "Packers",
      "Panthers",
      "Raiders",
      "Rams",
      "Ravens",
      "Commanders",
      "Saints",
      "Seahawks",
      "Steelers",
      "Buccaneers",
      "Texans",
      "Titans",
      "Vikings",
    ],
    used_picks: ["Lions"],
    current_pick: "Buccaneers",
    user_id: 2,
  },
  {
    available_picks: [
      "49ers",
      "Bears",
      "Bengals",
      "Bills",
      "Broncos",
      "Browns",
      "Cardinals",
      "Chargers",
      "Chiefs",
      "Cowboys",
      "Dolphins",
      "Eagles",
      "Falcons",
      "Giants",
      "Jaguars",
      "Jets",
      "Packers",
      "Panthers",
      "Raiders",
      "Rams",
      "Ravens",
      "Commanders",
      "Saints",
      "Seahawks",
      "Steelers",
      "Buccaneers",
      "Texans",
      "Titans",
      "Vikings",
    ],
    used_picks: ["Lions", "Colts", "Patriots"],
    current_pick: "Titans",
    user_id: 3,
  },
];

const seedTrack = () => Track.bulkCreate(trackData);

module.exports = seedTrack;
