const express = require("express");
const { requireUser } = require("./require-user");
const { ValidationError } = require("../lib/errors");

function exactEndpointBody(body) { if (!body || typeof body !== "object" || Array.isArray(body) || Object.keys(body).join(",") !== "endpoint" || typeof body.endpoint !== "string" || body.endpoint.length > 2048) throw new ValidationError("Push device request is invalid"); try { if (new URL(body.endpoint).protocol !== "https:") throw new Error(); } catch (_error) { throw new ValidationError("Push device request is invalid"); } return body.endpoint; }
function createPushRouter({ service, getAccess, featureConfiguration, pushConfiguration }) {
  const router = express.Router(); router.use(requireUser); router.use((req, res, next) => { res.set("Cache-Control", "private, no-store"); const length = Number(req.get("content-length") || 0); if (!Number.isFinite(length) || length > 8192) return res.status(413).json({ code: "PAYLOAD_TOO_LARGE", message: "Push setup request is too large" }); return next(); });
  async function authorize(req) { const access = await getAccess({ userId: req.session.user_id, systemAvailable: featureConfiguration.pickRemindersSystemAvailable }); return access.effective === true; }
  router.get("/configuration", async (req, res, next) => { try { if (!await authorize(req)) return res.status(404).json({ code: "NOT_FOUND", message: "Push setup is unavailable" }); const available = featureConfiguration.pickRemindersPushDeliveryAvailable === true && pushConfiguration.ready === true; return res.json({ state: available ? "AVAILABLE" : "TEMPORARILY_UNAVAILABLE", publicKey: available ? pushConfiguration.vapidPublicKey : null }); } catch (error) { return next(error); } });
  router.post("/status", async (req, res, next) => { try { if (!await authorize(req)) return res.status(404).json({ code: "NOT_FOUND", message: "Push setup is unavailable" }); return res.json(await service.status({ userId: req.session.user_id, endpoint: exactEndpointBody(req.body) })); } catch (error) { return next(error); } });
  router.put("/subscription", async (req, res, next) => { try { if (!await authorize(req) || !pushConfiguration.ready || featureConfiguration.pickRemindersPushDeliveryAvailable !== true) return res.status(503).json({ code: "UNAVAILABLE", message: "Push setup is temporarily unavailable" }); if (!req.body || Object.keys(req.body).join(",") !== "subscription") throw new ValidationError("Push subscription request is invalid"); return res.json(await service.register({ userId: req.session.user_id, subscription: req.body.subscription })); } catch (error) { return next(error); } });
  router.delete("/subscription", async (req, res, next) => { try { if (!await authorize(req)) return res.status(404).json({ code: "NOT_FOUND", message: "Push setup is unavailable" }); return res.json(await service.disableCurrent({ userId: req.session.user_id, endpoint: exactEndpointBody(req.body) })); } catch (error) { return next(error); } });
  router.delete("/subscriptions", async (req, res, next) => { try { if (!await authorize(req)) return res.status(404).json({ code: "NOT_FOUND", message: "Push setup is unavailable" }); if (req.body && Object.keys(req.body).length) throw new ValidationError("Disable-all request is invalid"); return res.json(await service.disableAll({ userId: req.session.user_id })); } catch (error) { return next(error); } });
  return router;
}
module.exports = { createPushRouter };
