const test = require("node:test"); const databaseUrl = process.env.TEST_DATABASE_URL;
if (!databaseUrl) test("verified email reminders", { skip: "TEST_DATABASE_URL is not set" }, () => {});
else {
  process.env.NODE_ENV = "test"; const assert = require("node:assert/strict");
  const { sequelize, User, ReminderPreference, EmailReminderVerification, EmailVerificationRequest, EmailOptOutToken, EmailProviderHealth } = require("../../models");
  const { migrateEmptyTestDatabase } = require("../support/migrate-test-database"); const { createEmailTokenCryptography } = require("../../server/modules/reminders/email-token-cryptography"); const { createEmailReminderService } = require("../../server/modules/reminders/email-reminder-service"); const { createEmailProviderHealthService } = require("../../server/modules/reminders/email-provider-health-service");
  const key = Buffer.alloc(32, 9).toString("base64"); const configuration = { ready: true, publicAppOrigin: "https://example.test", currentKey: { key, version: "v1" }, previousKey: null };
  test.beforeEach(async () => { await migrateEmptyTestDatabase(sequelize); }); test.after(async () => sequelize.close());
  async function user(name = "email-user") { return User.create({ first_name: "Email", last_name: "User", username: name, email: `${name}@example.test`, password: "safe-test-password" }); }
  function harness({ at = new Date("2026-09-01T12:00:00Z"), credentialVersion = "credential-v1", classifications = ["ACCEPTED"] } = {}) { let clock = at; const sent = []; const outcomes = [...classifications]; const cryptography = createEmailTokenCryptography({ current: configuration.currentKey }); const health = createEmailProviderHealthService({ credentialVersion, logger: { info() {}, warn() {} } }); const service = createEmailReminderService({ cryptography, providerHealth: health, configuration, now: () => clock, setupTransport: { sendVerification: async (message) => { sent.push(message); return { classification: outcomes.shift() || "ACCEPTED" }; } }, logger: { info() {} } }); return { cryptography, health, sent, service, setTime(value) { clock = value; } }; }
  test("verification is hashed, single-use, atomic with enable, and survives ordinary disable", async () => { const target = await user(); const h = harness(); assert.deepEqual(await h.service.requestVerification(target.id), { state: "VERIFICATION_PENDING", retryAfterSeconds: 600, message: "Verification email sent. Check your inbox and spam folder. The link expires in 24 hours." }); assert.equal(h.sent.length, 1); assert.equal((await EmailVerificationRequest.findOne()).token_digest.includes(h.sent[0].token), false); assert.equal((await h.service.consumeVerification(h.sent[0].token)).success, true); assert.equal((await ReminderPreference.findByPk(target.id)).email_enabled, true); assert.equal(await EmailReminderVerification.count(), 1); assert.equal((await h.service.consumeVerification(h.sent[0].token)).success, false); assert.equal((await h.service.setEnabled(target.id, false)).state, "USER_DISABLED"); assert.equal(await EmailReminderVerification.count(), 1); assert.equal((await h.service.setEnabled(target.id, true)).state, "ENABLED"); });
  test("new request supersedes old and durable limits apply at boundaries", async () => { const target = await user("limits"); const h = harness(); await h.service.requestVerification(target.id); const first = h.sent[0].token; h.setTime(new Date("2026-09-01T12:10:00Z")); await h.service.requestVerification(target.id); assert.equal((await h.service.consumeVerification(first)).success, false); for (let hour = 1; hour <= 3; hour += 1) { h.setTime(new Date(`2026-09-01T${12 + hour}:10:00Z`)); await h.service.requestVerification(target.id); } h.setTime(new Date("2026-09-01T16:10:00Z")); const limited = await h.service.requestVerification(target.id); assert.equal(limited.state, "RATE_LIMITED"); assert.equal(limited.retryAfterSeconds > 0, true); assert.equal(await EmailVerificationRequest.count(), 5); });
  test("concurrent requests cannot bypass the ten-minute limit", async () => { const target = await user("concurrent-limit"); const h = harness(); const results = await Promise.all([h.service.requestVerification(target.id), h.service.requestVerification(target.id)]); assert.equal(results.filter(({ state }) => state === "RATE_LIMITED").length, 1); assert.equal(await EmailVerificationRequest.count(), 1); assert.equal(h.sent.length, 1); });
  test("account email change invalidates enable and delivery without storing plaintext evidence", async () => { const target = await user("changed"); const h = harness(); await h.service.requestVerification(target.id); await h.service.consumeVerification(h.sent[0].token); await target.update({ email: "new-address@example.test" }); assert.equal((await h.service.setEnabled(target.id, true)).state, "VERIFICATION_REQUIRED"); assert.equal((await h.service.deliveryEligibility({ userId: target.id })).eligible, false); assert.equal((await EmailReminderVerification.findByPk(target.id)).email_digest.includes("new-address"), false); });
  test("opt-out is password-free, idempotent, email-only, rotated, and cascades on deletion", async () => { const target = await user("optout"); const h = harness(); await h.service.requestVerification(target.id); await h.service.consumeVerification(h.sent[0].token); await ReminderPreference.update({ push_enabled: true }, { where: { user_id: target.id } }); const raw = await sequelize.transaction((transaction) => h.service.issueOptOut(target.id, transaction)); assert.equal((await EmailOptOutToken.findOne()).token_digest.includes(raw), false); await h.service.optOut(raw); await h.service.optOut(raw); const preference = await ReminderPreference.findByPk(target.id); assert.equal(preference.email_enabled, false); assert.equal(preference.push_enabled, true); await target.destroy(); assert.equal(await EmailReminderVerification.count(), 0); assert.equal(await EmailVerificationRequest.count(), 0); assert.equal(await EmailOptOutToken.count(), 0); });
  test("Gmail authentication breaker is shared and only a new credential version recovers", async () => { const first = harness(); assert.equal((await first.health.readiness()).ready, true); assert.equal((await first.health.open()).opened, true); assert.equal((await first.health.open()).opened, false); const sameVersion = harness(); assert.equal((await sameVersion.health.readiness()).ready, false); const rotated = harness({ credentialVersion: "credential-v2" }); assert.equal((await rotated.health.readiness()).ready, true); assert.equal((await EmailProviderHealth.findByPk("GMAIL")).state, "CLOSED"); });
  test("status exposes resend timing only for potentially delivered requests", async () => { const target = await user("resend-status"); const h = harness({ classifications: ["ACCEPTED"] }); assert.deepEqual(await h.service.status(target.id), { state: "OFF", maskedDestination: "r•••@example.test", retryAfterSeconds: 0, hasPreviousRequest: false }); await h.service.requestVerification(target.id); h.setTime(new Date("2026-09-01T12:00:01Z")); assert.deepEqual(await h.service.status(target.id), { state: "VERIFICATION_PENDING", maskedDestination: "r•••@example.test", retryAfterSeconds: 599, hasPreviousRequest: true }); h.setTime(new Date("2026-09-01T12:10:00Z")); assert.deepEqual(await h.service.status(target.id), { state: "VERIFICATION_PENDING", maskedDestination: "r•••@example.test", retryAfterSeconds: 0, hasPreviousRequest: true }); });
  test("definite send failures preserve old links and consume no resend capacity", async () => { const target = await user("definite-failure"); const h = harness({ classifications: ["ACCEPTED", "TEMPORARY_FAILURE", "ACCEPTED"] }); const first = await h.service.requestVerification(target.id); assert.equal(first.retryAfterSeconds, 600); const original = h.sent[0].token; h.setTime(new Date("2026-09-01T12:10:00Z")); assert.equal((await h.service.requestVerification(target.id)).state, "TEMPORARILY_UNAVAILABLE"); assert.equal((await EmailVerificationRequest.findAll({ order: [["id", "ASC"]] }))[0].superseded_at, null); assert.equal((await h.service.status(target.id)).retryAfterSeconds, 0); assert.equal((await h.service.requestVerification(target.id)).state, "VERIFICATION_PENDING"); assert.equal((await h.service.consumeVerification(original)).success, false); });
  test("ambiguous sends consume limits and supersede older usable links", async () => { const target = await user("ambiguous-resend"); const h = harness({ classifications: ["ACCEPTED", "UNKNOWN"] }); await h.service.requestVerification(target.id); const original = h.sent[0].token; h.setTime(new Date("2026-09-01T12:10:00Z")); const resent = await h.service.requestVerification(target.id); assert.equal(resent.retryAfterSeconds, 600); assert.equal((await h.service.status(target.id)).state, "VERIFICATION_PENDING"); assert.equal((await h.service.requestVerification(target.id)).state, "RATE_LIMITED"); assert.equal((await h.service.consumeVerification(original)).success, false); });
}
